# Generated by Django 6.0.5 on 2026-05-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('kg_co2e_per_unit', models.DecimalField(decimal_places=6, max_digits=12)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plant_code', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP Flat File'), ('UTILITY', 'Utility Portal CSV'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('filename', models.CharField(blank=True, max_length=512)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imports', to='api.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='RawDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('raw_json', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='api.dataimport')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField(blank=True, choices=[(1, 'Scope 1 – Direct'), (2, 'Scope 2 – Purchased Energy'), (3, 'Scope 3 – Value Chain')], null=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('sub_category', models.CharField(blank=True, max_length=100)),
                ('activity_date_start', models.DateField(blank=True, null=True)),
                ('activity_date_end', models.DateField(blank=True, null=True)),
                ('original_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=50)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged / Suspicious'), ('ERROR', 'Error – Could Not Parse')], default='PENDING', max_length=20)),
                ('validation_warnings', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('edit_note', models.TextField(blank=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('emission_factor_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.emissionfactor')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facility')),
                ('import_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.dataimport')),
                ('raw_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rawdatarecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='facility',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='api.tenant'),
        ),
    ]
