# Generated by Django 6.0.5 on 2026-05-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emissionfactor',
            unique_together={('category', 'unit')},
        ),
    ]
